version: '3.9'

services:
  java_db:
      container_name: java_db
      image: postgres:14-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: simple_bookstore

  java_api:
    container_name: java_api
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/simple_bookstore
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=secret
    depends_on:
      - java_db
