version: '3.9'

services:
  postgres:
      image: postgres:14-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: simple_bookstore

  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/simple_bookstore
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=secret
    depends_on:
      - postgres
